name: t32_cbmg
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.3
  - asttokens=2.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - decorator=5.1.1
  - executing=1.2.0
  - ipython=8.6.0
  - jedi=0.18.1
  - libffi=3.4.2
  - libsqlite=3.40.0
  - libzlib=1.2.13
  - matplotlib-inline=0.1.6
  - ncurses=6.3
  - openssl=3.0.7
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.3.1
  - prompt-toolkit=3.0.32
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - python=3.11.0
  - readline=8.1.2
  - setuptools=65.5.1
  - six=1.16.0
  - stack_data=0.6.1
  - tk=8.6.12
  - traitlets=5.5.0
  - tzdata=2022f
  - wcwidth=0.2.5
  - wheel=0.38.4
  - xz=5.2.6
  - pip:
    - accessible-pygments==0.0.5
    - alabaster==0.7.16
    - attrs==24.2.0
    - babel==2.16.0
    - beautifulsoup4==4.12.3
    - certifi==2024.8.30
    - charset-normalizer==3.4.0
    - click==8.1.7
    - comm==0.2.2
    - debugpy==1.8.7
    - docutils==0.20.1
    - fastjsonschema==2.20.0
    - greenlet==3.1.1
    - idna==3.10
    - imagesize==1.4.1
    - importlib-metadata==8.5.0
    - ipykernel==6.29.5
    - jinja2==3.1.4
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - jupyter-book==1.0.3
    - jupyter-cache==1.0.0
    - jupyter-client==8.6.3
    - jupyter-core==5.7.2
    - latexcodec==3.0.0
    - linkify-it-py==2.0.3
    - markdown-it-py==3.0.0
    - markupsafe==3.0.1
    - mdit-py-plugins==0.4.2
    - mdurl==0.1.2
    - myst-nb==1.1.2
    - myst-parser==2.0.0
    - nbclient==0.10.0
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - packaging==24.1
    - platformdirs==4.3.6
    - psutil==6.0.0
    - pybtex==0.24.0
    - pybtex-docutils==1.0.3
    - pydata-sphinx-theme==0.15.4
    - pygments==2.18.0
    - python-dateutil==2.9.0.post0
    - pyyaml==6.0.2
    - pyzmq==26.2.0
    - referencing==0.35.1
    - requests==2.32.3
    - rpds-py==0.20.0
    - snowballstemmer==2.2.0
    - soupsieve==2.6
    - sphinx==7.4.7
    - sphinx-book-theme==1.1.3
    - sphinx-comments==0.0.3
    - sphinx-copybutton==0.5.2
    - sphinx-design==0.6.1
    - sphinx-external-toc==1.0.1
    - sphinx-jupyterbook-latex==1.0.0
    - sphinx-multitoc-numbering==0.1.3
    - sphinx-thebe==0.3.1
    - sphinx-togglebutton==0.3.2
    - sphinxcontrib-applehelp==2.0.0
    - sphinxcontrib-bibtex==2.6.3
    - sphinxcontrib-devhelp==2.0.0
    - sphinxcontrib-htmlhelp==2.1.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==2.0.0
    - sphinxcontrib-serializinghtml==2.0.0
    - sqlalchemy==2.0.35
    - tabulate==0.9.0
    - tornado==6.4.1
    - typing-extensions==4.12.2
    - uc-micro-py==1.0.3
    - urllib3==2.2.3
    - zipp==3.20.2